stages:
  - test
  - deploy

.gradle:
  before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches

server » test:
  stage: test
  image: openjdk:11
  extends: [ .gradle ]
  script:
    - "./gradlew :server:test"

telegram:
  stage: deploy
  image: registry.gitlab.com/clovis-ai/dotfiles:latest
  needs: [ ]
  script:
    - git changelog --format telegram-html --incoming >changelog
    - announce-telegram changelog "$CHAT_IDS"
  only:
    - master
