stages:
  - build
  - test
  - deploy

.gradle:
  before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches

server » build:
  stage: build
  image: openjdk:11
  extends: [ .gradle ]
  before_script:
    - mkdir -p bin/server-zip
  script:
    - "./gradlew :server:distZip"
    - mv server/build/distributions/*.zip bin/server-zip/
  artifacts:
    paths:
      - bin/server-zip/

.requiresServer:
  needs:
    - server » build
  dependencies:
    - server » build
  before_script:
    - mkdir -p bin/server
    - unzip bin/server-zip/server-*.zip -d bin/server/
    - ./bin/server/server-*/bin/server &

client » test jvm:
  stage: test
  image: openjdk:11
  extends: [ .gradle, .requiresServer ]
  script:
    - "./gradlew :client:jvmTest"
  artifacts:
    reports:
      junit: client/build/test-results/jvmTest/**/TEST-*.xml

server » test:
  stage: test
  image: openjdk:11
  extends: [ .gradle ]
  needs: [ ]
  script:
    - "./gradlew :server:test"
  artifacts:
    reports:
      junit: server/build/test-results/test/**/TEST-*.xml

telegram:
  stage: deploy
  image: registry.gitlab.com/clovis-ai/dotfiles:latest
  needs: [ ]
  script:
    - git changelog --format telegram-html --incoming >changelog
    - announce-telegram changelog "$CHAT_IDS"
  only:
    - master
