stages:
  - build
  - test
  - deploy

variables:
  TEST_DB_IMAGE: "$CI_REGISTRY_IMAGE/mariadb-client:$CI_PIPELINE_IID"
  RELEASE_DB_IMAGE: "$CI_REGISTRY_IMAGE/mariadb-client:latest"
  OPENJDK_IMAGE: "openjdk:11"

.gradle:
  script: &prepare_gradle
    - export GRADLE_USER_HOME=$(pwd)/.gradle
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches

telegram:
  stage: deploy
  image: registry.gitlab.com/clovis-ai/dotfiles:latest
  needs: [ ]
  script:
    - git changelog --format telegram-html --incoming >changelog
    - announce-telegram changelog "$CHAT_IDS"
  only:
    - master
