variables:
  TEST_DB_IMAGE: "$CI_REGISTRY_IMAGE/mariadb-client:$CI_PIPELINE_IID"
  RELEASE_DB_IMAGE: "$CI_REGISTRY_IMAGE/mariadb-client:latest"
  OPENJDK_IMAGE: "openjdk:11"
  CASSANDRA_IMAGE: "cassandra:4.0"

.gradle:
  script: &prepare_gradle
    - export GRADLE_USER_HOME=$(pwd)/.gradle
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches

.database:
  services:
    - $CASSANDRA_IMAGE
  script: &prepare_database
    - cp core/database/src/main/resources/application.gitlab.conf core/database/src/main/resources/application.conf

core-jvm-test:
  image: $OPENJDK_IMAGE
  extends: [ .gradle ]
  needs: [ ]
  before_script:
    - *prepare_gradle
  script:
    - ./gradlew core:jvmTest
  artifacts:
    reports:
      junit: core/build/test-results/**/TEST-*.xml
    when: always
    paths:
      - core/build/reports/tests/

money-database-test:
  image: $OPENJDK_IMAGE
  extends: [ .gradle, .database ]
  needs: [ ]
  before_script:
    - *prepare_gradle
    - *prepare_database
  script:
    - ./gradlew money.database:test
  artifacts:
    reports:
      junit: money.database/build/test-results/**/TEST-*.xml
    when: always
    paths:
      - money.database/build/reports/tests/

telegram:
  stage: deploy
  image: registry.gitlab.com/clovis-ai/dotfiles:latest
  needs: [ ]
  script:
    - git changelog --format telegram-html --incoming >changelog
    - announce-telegram changelog "$CHAT_IDS"
  only:
    - master
