stages:
  - docker
  - build
  - test
  - deploy
  - notify

variables:
  openjdk_image: "openjdk:11"
  cassandra_image: "cassandra:4.0"

  clovis_jwt_secret: "secret"

include:
  - local: ".gitlab/ci/gradle.gitlab-ci.yml"
  - local: ".gitlab/ci/docker.gitlab-ci.yml"
  - local: ".gitlab/ci/database.gitlab-ci.yml"
  - local: ".gitlab/ci/backend.gitlab-ci.yml"
  - local: ".gitlab/ci/test.gitlab-ci.yml"
  - local: ".gitlab/ci/telegram.gitlab-ci.yml"
  - local: ".gitlab/ci/pages.gitlab-ci.yml"
