stages:
  - build
  - test
  - deploy

.gradle:
  script: &prepare_gradle
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - cp server/gradle-local.gitlab.properties server/gradle-local.properties
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches

.requiresDatabase:
  services:
    - mysql
  variables:
    MYSQL_DATABASE: clovis
    MYSQL_ROOT_PASSWORD: super_safe_password
  script: &prepare_database
    - apt-get install -y mariadb-client
    - <server/src/main/resources/sql/init.sql mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"

server » build:
  stage: build
  image: openjdk:11-buster
  extends: [ .gradle ]
  before_script:
    - *prepare_gradle
  script:
    - mkdir -p bin/server-zip
    - "./gradlew :server:distZip"
    - mv server/build/distributions/*.zip bin/server-zip/
  artifacts:
    paths:
      - bin/server-zip/

.requiresServer:
  needs:
    - server » build
  dependencies:
    - server » build
  before_script:
    - mkdir -p bin/server
    - unzip bin/server-zip/server-*.zip -d bin/server/
    - ./bin/server/server-*/bin/server &

client » test jvm:
  stage: test
  image: openjdk:11
  extends: [ .gradle, .requiresServer, .requiresDatabase ]
  before_script:
    - *prepare_gradle
    - *prepare_database
  script:
    - "./gradlew :client:jvmTest"
  artifacts:
    reports:
      junit: client/build/test-results/jvmTest/**/TEST-*.xml

server » test:
  stage: test
  image: openjdk:11
  extends: [ .gradle, .requiresDatabase ]
  before_script:
    - *prepare_gradle
    - *prepare_database
  needs: [ ]
  script:
    - "./gradlew :server:test :server:printCoverage"
  artifacts:
    reports:
      junit: server/build/test-results/test/**/TEST-*.xml
  coverage: '/^Coverage:\s(\d+\.\d+%)/'

telegram:
  stage: deploy
  image: registry.gitlab.com/clovis-ai/dotfiles:latest
  needs: [ ]
  script:
    - git changelog --format telegram-html --incoming >changelog
    - announce-telegram changelog "$CHAT_IDS"
  only:
    - master
